apiVersion: v1
kind: Service
metadata:
  name: multiplication-microsvc-service
spec:
  selector:
    app: multiplication-microsvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: NodePort
