apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-microsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition-microsvc
  template:
    metadata:
      labels:
        app: addition-microsvc
    spec:
      containers:
      - name: addition-microsvc-container
        image: addition-microsvc-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
