apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-microsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-microsvc
  template:
    metadata:
      labels:
        app: timestamp-microsvc
    spec:
      containers:
      - name: timestamp-microsvc-container
        image: timestamp-microsvc-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3003