apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtraction-microsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtraction-microsvc
  template:
    metadata:
      labels:
        app: subtraction-microsvc
    spec:
      containers:
      - name: subtraction-microsvc-container
        image: subtraction-microsvc-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
