apiVersion: v1
kind: Service
metadata:
  name: subtraction-microsvc-service
spec:
  selector:
    app: subtraction-microsvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
  type: NodePort
