apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand-string-microsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-string-microsvc
  template:
    metadata:
      labels:
        app: rand-string-microsvc
    spec:
      containers:
      - name: rand-string-microsvc-container
        image: rand-string-microsvc-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3005