apiVersion: v1
kind: Service
metadata:
  name: rand-string-microsvc-service
spec:
  selector:
    app: rand-string-microsvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3005
  type: ClusterIP